spring:
  application:
    name: ts-gateway
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health
ts:
  services:
    user-service-uri: ${TS_USER_SERVICE_URI:http://localhost:8080}
    task-service-uri: ${TS_TASK_SERVICE_URI:http://localhost:8081}
